version: "3.7"

services:
  orders:
    container_name: orders_service
    image: orders:latest
    build: ./orders
    env_file:
      - ./orders/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/orders
      - /orders/node_modules
    networks:
      - app-net
    links:
      - redis
    depends_on:
      - redis
      - db
  products:
    container_name: products_service
    restart: always
    image: products:latest
    build: ./products
    env_file:
      - ./products/.env
    ports:
      - "3002:3002"
    volumes:
      - .:/products
      - /products/node_modules
    depends_on:
      - db
    networks:
      - app-net
  gateway:
    container_name: api_gateway
    image: gateway:latest
    build: ./gateway
    env_file:
      - ./gateway/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/gateway
      - /gateway/node_modules
    depends_on:
      - redis
    links:
      - redis
    networks:
      - app-net
  db:
    container_name: db
    hostname: db
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root-db
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/db:/data/db
    networks:
      - app-net
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data/redis"
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    networks:
      - app-net
networks:
  app-net:
    driver: bridge